// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCntEl-wWiXKcmR8jEp-X2U1efzILDL9jM',
    appId: '1:20771917437:web:dcb80f45679afe75892b14',
    messagingSenderId: '20771917437',
    projectId: 'project-66428',
    authDomain: 'project-66428.firebaseapp.com',
    storageBucket: 'project-66428.firebasestorage.app',
    measurementId: 'G-HNVNP84Q38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs9zRM-12fmj6X172nsYulnH4DRatXR7Q',
    appId: '1:20771917437:android:03e4811522ac6c03892b14',
    messagingSenderId: '20771917437',
    projectId: 'project-66428',
    storageBucket: 'project-66428.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB2s00_jqJ2xFqFzgaN1rSWkIZ7cWwQGs',
    appId: '1:20771917437:ios:4e06f40e7a97f10a892b14',
    messagingSenderId: '20771917437',
    projectId: 'project-66428',
    storageBucket: 'project-66428.firebasestorage.app',
    iosClientId: '20771917437-a740mdpq3nj3nnhgafp9varmteaudt0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.compwaste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB2s00_jqJ2xFqFzgaN1rSWkIZ7cWwQGs',
    appId: '1:20771917437:ios:4e06f40e7a97f10a892b14',
    messagingSenderId: '20771917437',
    projectId: 'project-66428',
    storageBucket: 'project-66428.firebasestorage.app',
    iosClientId: '20771917437-a740mdpq3nj3nnhgafp9varmteaudt0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.compwaste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCntEl-wWiXKcmR8jEp-X2U1efzILDL9jM',
    appId: '1:20771917437:web:70dbb58140cd5d53892b14',
    messagingSenderId: '20771917437',
    projectId: 'project-66428',
    authDomain: 'project-66428.firebaseapp.com',
    storageBucket: 'project-66428.firebasestorage.app',
    measurementId: 'G-2WGK6G8W6T',
  );
}
